platform: linux

image_resource:
  type: docker-image
  source:
    repository: licensefinder/license_finder
    tag: latest

inputs:
- name: LicenseFinder

run:
  path: ./LicenseFinder/ci/scripts/test.sh

params:
  RUBY_VERSION_UNDER_TEST:
